# Use root/example as user/password credentials
version: '3.1'

services:

  api:
    build:
      context: ./server
      dockerfile: ../server/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # We only mount source code in development:
      - ./server:/usr/src/app
    restart: always

  mysql_db:
    image: mysql:5.7
    volumes:
      - mysql_db:/var/lib/mysql
    env_file:
      - .env 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  
volumes:
  mysql_db:
    driver: local



  # db:
  #   build:
  #     context: ./db
  #     dockerfile: ../db/Dockerfile


  #   # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #   # (this is just an example, not intended to be a production configuration)
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
